// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4LygyKbDPy6DCH12kHz-CbDfrSGpdzpU',
    appId: '1:412609966273:web:1cbe4d0a9ba5439d412440',
    messagingSenderId: '412609966273',
    projectId: 'gen12-64948',
    authDomain: 'gen12-64948.firebaseapp.com',
    storageBucket: 'gen12-64948.firebasestorage.app',
    measurementId: 'G-N9BBET8NQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8kng6yAfYKnA18rHuByh55ivrtQC9Wuk',
    appId: '1:412609966273:android:94f724b666e511a2412440',
    messagingSenderId: '412609966273',
    projectId: 'gen12-64948',
    storageBucket: 'gen12-64948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2mlo4_aFsOWY8c5IGvL9P9I7DUAV9IS8',
    appId: '1:412609966273:ios:3b45cf8491249815412440',
    messagingSenderId: '412609966273',
    projectId: 'gen12-64948',
    storageBucket: 'gen12-64948.firebasestorage.app',
    iosBundleId: 'com.design.design',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2mlo4_aFsOWY8c5IGvL9P9I7DUAV9IS8',
    appId: '1:412609966273:ios:3b45cf8491249815412440',
    messagingSenderId: '412609966273',
    projectId: 'gen12-64948',
    storageBucket: 'gen12-64948.firebasestorage.app',
    iosBundleId: 'com.design.design',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4LygyKbDPy6DCH12kHz-CbDfrSGpdzpU',
    appId: '1:412609966273:web:268452c14e09deb6412440',
    messagingSenderId: '412609966273',
    projectId: 'gen12-64948',
    authDomain: 'gen12-64948.firebaseapp.com',
    storageBucket: 'gen12-64948.firebasestorage.app',
    measurementId: 'G-1CNP7XH7QV',
  );
}
